### ISSUE TITLE
Feature request: ability to set a delay before a lock is activated

### ISSUE THREAD

**Issue by mstahl302** [tomkahn/lockmyphone_public#22]
I often want to take a break and surf onmy phone, but I end up getting lost in distraction and wasting a lot of time.

How about a feature that allows me to set a lock to start after a delay?  Then I can pre-commit to locking my phone after 5 minutes, then surf 5 minutes, knowing that I can't go over (unless I pay, of course.)

**Comment by tomkahn** [comment]
You're right, good idea.

**Comment by mstahl302** [comment]
Filed new request, #23
