### ISSUE TITLE
Does it work on chromebook? 

### ISSUE THREAD

**Issue by MattD4** [tomkahn/lockmyphone_public#4]
I've had some trouble trying to get it to work on my chromebook. I've been unable to disable battery optimisation on the app or to get it to auto start, does anyone have any advice?

**Comment by tomkahn** [comment]
Hi Matt, have you tried [dontkillmyapp.com](https://dontkillmyapp.com)? Did you find any instructions there? But it seems like [other people](https://github.com/OxfordHCC/tracker-control-android/issues/204) have issues with disabling battery optimization on their Chromebooks as well.
